const people=[{name:'Ananya',languages:['English','Malayalam'],topics:['stress','relationships','life'],bio:'Here to listen and support. Let’s talk.',detail:'A calm space to talk through a difficult day, relationships, or whatever is on your mind.',x:533,y:419,w:97,h:103},{name:'Rohit',languages:['English','Hindi'],topics:['college','work','stress'],bio:'A friendly listener. You can talk about anything.',detail:'From college transitions to work pressure, there is room to slow down and talk things through.',x:648,y:419,w:101,h:103},{name:'Meera',languages:['English','Tamil'],topics:['relationships','life','stress'],bio:'Happy to listen. Take your time.',detail:'You do not need to have the right words. Take your time and share only what feels comfortable.',x:766,y:419,w:101,h:103,busy:true},{name:'Arjun',languages:['English','Malayalam'],topics:['college','work','life'],bio:'Here for real conversations.',detail:'A friendly space for everyday worries, new beginnings, and the things you want to say out loud.',x:883,y:419,w:101,h:103}];
let topic='all';const cards=document.querySelector('#listener-cards');const dialog=document.querySelector('#dialog');const content=document.querySelector('#dialog-content');
function render(){const q=document.querySelector('#search').value.toLowerCase().trim();const result=people.filter(p=>(topic==='all'||p.topics.includes(topic))&&[p.name,...p.languages,...p.topics,p.bio].join(' ').toLowerCase().includes(q));cards.innerHTML=result.map(p=>`<article class="listener-card"><div class="portrait crop" style="--w:${p.w};--h:${p.h};--x:${p.x};--y:${p.y}"><img src="assets/reference.png" alt="${p.name}"></div><div class="card-info"><div class="card-name"><h4>${p.name}</h4><span class="status ${p.busy?'busy':''}">${p.busy?'Busy':'Online'}</span></div><p>${p.bio}</p><div class="languages">${p.languages.map(l=>`<span>${l}</span>`).join('')}</div><button class="button gold" data-profile="${p.name}">View profile</button></div></article>`).join('');document.querySelector('.empty').hidden=result.length>0;document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>profile(b.dataset.profile)));}
function open(html){content.innerHTML=html;dialog.showModal();document.body.style.overflow='hidden';}function close(){dialog.close();}dialog.addEventListener('close',()=>document.body.style.overflow='');document.querySelector('#close-dialog').onclick=close;dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
function profile(name){const p=people.find(p=>p.name===name);open(`<span class="eyebrow">MEET YOUR LISTENER</span><h2>${p.name}</h2><p>${p.detail}</p><span class="modal-label">LANGUAGES</span><p>${p.languages.join(' · ')}</p><span class="modal-label">HAPPY TO TALK ABOUT</span><p>${p.topics.map(x=>x[0].toUpperCase()+x.slice(1)).join(' · ')}</p><p class="preview-note">This is a sample profile in the website preview. Live availability and conversations are not connected yet.</p><button class="button gold" id="back-listeners">Explore other listeners</button>`);document.querySelector('#back-listeners').onclick=close;}
document.querySelector('#search').addEventListener('input',render);document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{topic=b.dataset.topic;document.querySelectorAll('[data-topic]').forEach(c=>{c.classList.toggle('selected',c===b);c.setAttribute('aria-pressed',String(c===b));});render();});
document.querySelector('#previous').onclick=()=>cards.scrollBy({left:-cards.clientWidth,behavior:'smooth'});document.querySelector('#next').onclick=()=>cards.scrollBy({left:cards.clientWidth,behavior:'smooth'});
const menu=document.querySelector('.menu');const nav=document.querySelector('#navigation');menu.onclick=()=>{const expanded=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(expanded));menu.setAttribute('aria-label',expanded?'Close navigation':'Open navigation');nav.classList.toggle('open',expanded);};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');nav.querySelectorAll('a').forEach(n=>n.classList.toggle('active',n===a));});
document.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>open('<span class="eyebrow">YOU BELONG HERE</span><h2>A place to be yourself.</h2><p>Make room for real conversation, shared experiences, and a little more connection.</p><ul><li>Start with a one-to-one conversation.</li><li>Find connection through shared interests.</li><li>Share at your own pace and respect each other’s boundaries.</li></ul><p>Community sign-up is not connected in this preview.</p><a class="button gold" href="#listeners" onclick="document.querySelector(\'#dialog\').close()">Meet the listeners</a>'));
document.querySelector('[data-community]').onclick=()=>open('<span class="eyebrow">OUR COMMUNITY</span><h2>Small circles.<br>Meaningful connection.</h2><p>A conversation over chai. An evening of music. A quiet moment with someone who understands.</p><p>Smile Guidance is a space to connect through listening, shared interests, and everyday experiences. You choose how much you want to share.</p><a class="button gold" href="#moments" onclick="document.querySelector(\'#dialog\').close()">Explore community moments</a>');
document.querySelector('[data-story]').onclick=()=>open('<span class="eyebrow">OUR STORY</span><h2>Being heard can make a difference.</h2><p>Smile Guidance begins with a simple belief: everyone deserves a place where they can speak openly and be met with kindness.</p><p>Our vision is a community built on real conversations — where listening matters as much as speaking, and connection begins without judgement.</p><p>Peer listening offers company and connection. It does not replace professional counselling or emergency care.</p>');
document.querySelector('#all-moments').onclick=e=>{const expanded=document.querySelector('.moment-grid').classList.toggle('expanded');e.target.textContent=expanded?'Show fewer moments':'View all moments';e.target.setAttribute('aria-expanded',String(expanded));};
document.querySelectorAll('[data-moment]').forEach(b=>b.onclick=()=>{const labels=['A little warmth. A lot of listening.','Come as you are.','Sometimes, company is enough.'];const descriptions=['Shared stories and a slow evening around the fire.','Music, conversation, and space for everyone at the circle.','A quiet sunset, with people who make you feel at home.'];open(`<span class="eyebrow">COMMUNITY MOMENTS</span><h2>${labels[+b.dataset.moment]}</h2>${b.querySelector('.crop').outerHTML}<p>${descriptions[+b.dataset.moment]}</p>`);});render();
